# Generated by Django 5.2.7 on 2025-11-05 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='folder',
            name='is_pinned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name='folder',
            index=models.Index(fields=['workspace', 'is_pinned', '-created_at'], name='workspaces__workspa_f7ff85_idx'),
        ),
        migrations.AddConstraint(
            model_name='folder',
            constraint=models.UniqueConstraint(fields=('workspace', 'name'), name='unique_folder_name_per_workspace'),
        ),
    ]
