# Generated by Django 5.2.7 on 2025-11-07 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0002_folder_is_pinned_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workspace',
            name='category',
            field=models.CharField(blank=True, choices=[('PROJECT', 'Project'), ('OFFICE', 'Office'), ('TEAM', 'Team'), ('OTHER', 'Other')], max_length=255, null=True),
        ),
    ]
