# Generated by Django 5.2.7 on 2025-11-14 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_profile_email'),
        ('workspaces', '0003_alter_workspace_category'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='workspace',
            constraint=models.UniqueConstraint(fields=('owner', 'name'), name='unique_workspace_per_user'),
        ),
    ]
