# Generated by Django 5.2.9 on 2025-12-21 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0005_meeting_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='bot_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='meeting',
            name='calendar_event_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='meeting',
            name='metadata',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
