# Generated by Django 5.2.9 on 2025-12-21 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0006_meeting_bot_id_meeting_calendar_event_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='transcription_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
