# Generated by Django 5.2.9 on 2025-12-21 18:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0007_meeting_transcription_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='meetings', to='workspaces.folder'),
        ),
    ]
