# Generated by Django 5.2.16 on 2026-08-14 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0009_meeting_workspace'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meeting',
            name='folder',
        ),
        migrations.DeleteModel(
            name='Folder',
        ),
    ]
