# Generated by Django 5.2.16 on 2026-08-27 17:15

"""Drop `workspaces.Meeting`.

The table has never held a row. Meetings are recorded by recall-server and
live in its `MeetingTranscription` table; this model was left over from an
earlier design and kept a full CRUD API, admin page and filter set alive
around an empty table.

The one thing that genuinely read it was the GDPR data export, which is why
every export contained `meetings: []`. That was repointed at recall-server
first — see accounts/services.py::_export_meetings — so nothing reads this
table any more.
"""

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0010_remove_meeting_folder_delete_folder'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Meeting',
        ),
    ]
