# Generated by Django 5.2.7 on 2025-11-02 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='audience',
            field=models.CharField(blank=True, choices=[('COMPANY', 'Company'), ('PERSONAL', 'Personal')], max_length=50),
        ),
        migrations.AddField(
            model_name='profile',
            name='company',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='profile',
            name='position',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='profile',
            name='purpose',
            field=models.CharField(blank=True, choices=[('TEAM_MEETINGS', 'Internal team meetings'), ('SALES_CALLS', 'Client or sales calls'), ('TRAINING', 'Workshops or training'), ('BRAINSTORMING', 'Brainstorming sessions')], max_length=50),
        ),
    ]
