# Generated by Django 5.2.7 on 2025-11-05 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_audience_profile_company_profile_position_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='audience',
            field=models.CharField(blank=True, choices=[('COMPANY', 'Company'), ('PERSONAL', 'Personal')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='company',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='first_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='last_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='position',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='purpose',
            field=models.CharField(blank=True, choices=[('TEAM_MEETINGS', 'Internal team meetings'), ('SALES_CALLS', 'Client or sales calls'), ('TRAINING', 'Workshops or training'), ('BRAINSTORMING', 'Brainstorming sessions')], max_length=50, null=True),
        ),
    ]
