# Generated by Django 5.2.7 on 2025-11-07 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_profile_audience_alter_profile_company_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, help_text='User profile picture', null=True, upload_to='avatars/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
