# Generated by Django 5.2.7 on 2025-11-09 14:27

import accounts.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_profile_avatar_alter_profile_avatar_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, help_text='User profile picture', null=True, upload_to=accounts.models.avatar_upload_path),
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('LOGIN_SUCCESS', 'Login Successful'), ('LOGIN_FAILED', 'Login Failed'), ('profile_update', 'Profile Updated')], max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to='accounts.profile')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['profile', '-timestamp'], name='accounts_ac_profile_cb6c50_idx'), models.Index(fields=['activity_type'], name='accounts_ac_activit_12bf8b_idx')],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('meta_data', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('seen', models.BooleanField(default=False)),
                ('notify_type', models.CharField(choices=[('WARNING', 'Warning'), ('SUCCESS', 'Success'), ('DANGER', 'Danger')], default='SUCCESS', max_length=20, verbose_name='Status of the notification, warning, success or error')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='accounts.profile')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['owner', '-created_at'], name='accounts_no_owner_i_43e695_idx'), models.Index(fields=['seen'], name='accounts_no_seen_336eef_idx')],
            },
        ),
    ]
