# Generated by Django 5.2.7 on 2025-11-11 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_profile_avatar_activitylog_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitylog',
            name='meta_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='activity_type',
            field=models.CharField(choices=[('LOGIN_SUCCESS', 'Login Successful'), ('LOGIN_FAILED', 'Login Failed'), ('PROFILE_UPDATE', 'Profile Updated'), ('PASSWORD_CHANGED', 'Password changed')], max_length=255),
        ),
    ]
