# Generated by Django 5.2.7 on 2025-11-14 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_activitylog_meta_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='company_notes',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='purpose',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
