# Generated by Django 5.2.7 on 2025-11-14 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_profile_company_notes_alter_profile_purpose'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='sso_provider',
            field=models.CharField(blank=True, help_text='SSO provider: google, microsoft, email, etc.', max_length=50, null=True),
        ),
    ]
