# Generated by Django 5.2.7 on 2025-11-21 05:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_profile_first_login_profile_show_tour'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileStorage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_bytes', models.BigIntegerField(default=0)),
                ('total_mb', models.FloatField(default=0.0)),
                ('breakdown', models.JSONField(blank=True, default=dict)),
                ('calculated_at', models.DateTimeField(auto_now=True)),
                ('supabase_bytes', models.BigIntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='storage', to='accounts.profile')),
            ],
            options={
                'verbose_name_plural': 'User storage',
            },
        ),
    ]
