# Generated by Django 5.2.9 on 2025-12-08 11:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_profilestorage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='backup_exclusion_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='data_export_completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='data_exported',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='deletion_completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='deletion_requested_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='deletion_requested_by_ip',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='deletion_type',
            field=models.CharField(blank=True, choices=[('IMMEDIATE', 'Immediate Deletion'), ('GRACE_PERIOD', '7-Day Grace Period')], max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='deletion_verification_confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='deletion_verification_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='deletion_verification_token',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='profile',
            name='deletion_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='excluded_from_backups',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_eu_resident',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='legal_hold',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='legal_hold_approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='legal_holds_approved', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='profile',
            name='legal_hold_case_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='legal_hold_placed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='legal_hold_placed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='legal_holds_placed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='profile',
            name='legal_hold_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='legal_hold_reason_user_facing',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='legal_hold_review_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='privacy_regulation',
            field=models.CharField(default='GDPR', max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='retention_basis',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='profile',
            name='user_country',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.CreateModel(
            name='DeletionAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('pseudonymized', models.BooleanField(default=False)),
                ('pseudonymized_at', models.DateTimeField(blank=True, null=True)),
                ('profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.profile')),
            ],
        ),
    ]
