# Generated by Django 5.2.9 on 2025-12-10 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_profile_backup_exclusion_verified_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='stripe_customer_id',
            field=models.CharField(blank=True, help_text='Stripe Customer ID (for paid users)', max_length=100, null=True),
        ),
    ]
