# Generated by Django 5.2.16 on 2026-08-13 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_profile_stripe_subscription_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='subscription_plan',
            field=models.CharField(choices=[('free', 'Free'), ('clarity', 'Clarity'), ('insight', 'Insight'), ('alignment', 'Alignment')], default='free', max_length=20),
        ),
    ]
