# Generated by Django 5.2.16 on 2026-08-25 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_set_subscription_plan_db_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='auto_join_meetings',
            field=models.BooleanField(default=True),
        ),
    ]
