"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
from datetime import timedelta
from decouple import config, Csv
from django.core.files.storage import FileSystemStorage
import dj_database_url
from celery.schedules import crontab

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

LOG_DIR = BASE_DIR / 'logs'
LOG_DIR.mkdir(exist_ok=True)  # This fixes the error

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config(
    "DJANGO_SECRET_KEY",
    default="19WjHUSl2rb8h29fSRRQ62uJiJAfT8m1emybJYuNw5uHROfRPcqFXWZQFO90bDyxM2",
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config("DJANGO_DEBUG", default=False, cast=bool)

ALLOWED_HOSTS_LIST = config("ALLOWED_HOSTS")
ALLOWED_HOSTS = ALLOWED_HOSTS_LIST.split(",") if ALLOWED_HOSTS_LIST else []

CSRF_TRUSTED_ORIGINS = [f"https://{host}" for host in ALLOWED_HOSTS if host]

CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
]

CORS_ALLOW_METHODS = [
    "DELETE",
    "GET",
    "OPTIONS",
    "PATCH",
    "POST",
    "PUT",
]
CORS_ALLOW_ALL_ORIGINS = config("CORS_ALLOW_ALL_ORIGINS", default=False)
CORS_ALLOW_CREDENTIALS = True

origins_string = config("CORS_ALLOWED_ORIGINS", default="http://localhost:3000,http://127.0.0.1:3000")
CORS_ALLOWED_ORIGINS = [
    origin.strip()
    for origin in origins_string.split(",")
    if origin.strip()
]

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'django_filters',
    'django_extensions',
    'django_guid',
    'drf_spectacular',
    'rest_framework',
    'corsheaders',
    'storages',
    "django_celery_beat",

    'accounts',
    'workspaces',

]

MIDDLEWARE = [
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'core.middleware.CorrelationIDMiddleware',
    'django_guid.middleware.guid_middleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'core.middleware.ThrottleMonitorMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'accounts.middleware.SupabaseJWTAuthentication',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

MEDIA_ROOT = str(BASE_DIR / "media")
MEDIA_URL = "/media/"

WSGI_APPLICATION = 'core.wsgi.application'

# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases
DATABASES = {
    'default': dj_database_url.parse(config('DATABASE_URL'))
}
# REQUIRED for Supabase Pooler (Supavisor)
DATABASES['default']['OPTIONS'] = {
    'sslmode': 'require',           # SSL is mandatory
    'server_side_binding': True,    # Required in transaction mode
    'connect_timeout': 10,
}
# Reuse connections (optional but recommended)
DATABASES['default']['CONN_MAX_AGE'] = 0


SUPABASE_URL=config("SUPABASE_URL")
SUPABASE_ANON_KEY=config("SUPABASE_ANON_KEY")
SUPABASE_SERVICE_ROLE_KEY=config("SUPABASE_SERVICE_ROLE_KEY")
OPENAI_API_KEY=config("OPENAI_API_KEY")
REDIS_URL=config("REDIS_URL")
SUPABASE_JWT_SECRET=config("SUPABASE_JWT_SECRET")
SUPABASE_PROJECT_REF = config("SUPABASE_PROJECT_REF", default="fzluqkoqutihhpvrebxg")

USE_SUPABASE_STORAGE = config('USE_SUPABASE_STORAGE', default=False, cast=bool)

if USE_SUPABASE_STORAGE:
    print("✅ SUPABASE STORAGE ENABLED")

    AWS_ACCESS_KEY_ID = "000608598ee04264f80542603489602f"
    AWS_SECRET_ACCESS_KEY = "0ee222be7e073a47413a55f2e8b67790f6001415c8bf83c5f9eb8cf463fd05b9"
    AWS_STORAGE_BUCKET_NAME = config('SUPABASE_STORAGE_BUCKET', default='avatars')
    AWS_S3_ENDPOINT_URL = f"{config('SUPABASE_URL')}/storage/v1/s3"
    AWS_S3_REGION_NAME = config('SUPABASE_REGION', default='us-east-1')
    AWS_DEFAULT_ACL = 'private'
    AWS_S3_FILEOVERWRITE = False

    if not all([SUPABASE_URL, SUPABASE_SERVICE_ROLE_KEY]):
        raise ValueError("SUPABASE_URL and SUPABASE_SERVICE_ROLE_KEY are required")
else:
    print("❌ SUPABASE STORAGE DISABLED")



STORAGES = {
    "default": {
        "BACKEND": "core.storage.SupabaseSignedStorage" if USE_SUPABASE_STORAGE else "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}

STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

AVATAR_MAX_SIZE = config("AVATAR_MAX_SIZE", default=5 * 1024 * 1024 ) # default 5 MB in bytes

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


FRONTEND_CONFIG = {
    "FRONTEND_URL": config("FRONTEND_URL", default="http://localhost:3000/"),
    "PASSWORD_RESET_URL": "password/reset/confirm/",
    "EMAIL_CONFIRM_URL": "verify_email/",
}

EMAIL_BACKEND = config(
    "DJANGO_EMAIL_BACKEND", default="django.core.mail.backends.console.EmailBackend",
)
DEFAULT_FROM_EMAIL = "Invite Ellie - No Reply <no-reply@inviteellie.ai>"

EMAIL_HOST = config('EMAIL_HOST', default='localhost')
EMAIL_PORT = config('EMAIL_PORT', cast=int, default=587)
EMAIL_HOST_USER = config('EMAIL_HOST_USER', default='')
EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD', default='')
EMAIL_USE_TLS = config('EMAIL_USE_TLS', default=True, cast=bool)
EMAIL_USE_SSL = config('EMAIL_USE_SSL', default=False, cast=bool)

SERVER_EMAIL = config('SERVER_EMAIL', default='webmaster@localhost')

EMAIL_SUBJECT_PREFIX = config('EMAIL_SUBJECT_PREFIX', default='')


CELERY_TASK_ALWAYS_EAGER = config("CELERY_TASK_ALWAYS_EAGER", default=True, cast=bool)
CELERY_TASK_EAGER_PROPAGATES = config("CELERY_TASK_EAGER_PROPAGATES", default=True, cast=bool)
CELERY_BEAT_SCHEDULER = "django_celery_beat.schedulers:DatabaseScheduler"
CELERY_TIMEZONE = 'UTC'


CELERY_BEAT_SCHEDULE = {
    'check-deletion-grace-periods': {
        'task': 'accounts.tasks.check_deletion_grace_periods',
        'schedule': crontab(minute=0, hour=3),
        'options': {'queue': 'celery'},
    },
    'daily-all-users-storage': {
        'task': 'accounts.tasks.calculate_all_users_storage',
        'schedule': crontab(minute=0, hour=2),  # 2 AM UTC daily
    },
    'daily-delete-old-meetings': {
        'task': 'workspaces.tasks.nightly_storage_maintenance',
        'schedule': crontab(minute=30, hour=3),  # Every day at 3:30 AM UTC
        'options': {'queue': 'celery'},
    },
    'monthly-supabase-orphan-check': {
        'task': 'accounts.tasks.monthly_supabase_orphan_check',
        'schedule': crontab(minute=0, hour=4, day_of_month=1),  # 1st day of every month at 4:00 AM UTC
        'options': {'queue': 'celery'},
    },
}

if CELERY_TASK_ALWAYS_EAGER != True and CELERY_TASK_EAGER_PROPAGATES != True:
    CELERY_BROKER_URL = config("CELERY_BROKER_URL", default='redis://localhost:6379/0')
    # Add password if set: 'redis://:your_password@10.0.0.8:6379/0'
    CELERY_RESULT_BACKEND = config("CELERY_RESULT_BACKEND", default='redis://localhost:6379/1')
    CELERY_ACCEPT_CONTENT = ['json']
    CELERY_TASK_SERIALIZER = 'json'
    CELERY_RESULT_SERIALIZER = 'json'

REST_FRAMEWORK = {
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 10,
    'PAGE_SIZE_QUERY_PARAM': 'page_size',
    'DEFAULT_AUTHENTICATION_CLASSES': [],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_FILTER_BACKENDS': [
        'django_filters.rest_framework.DjangoFilterBackend',
        'rest_framework.filters.SearchFilter',
        'rest_framework.filters.OrderingFilter',
    ],
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle',
    ],
    'DEFAULT_THROTTLE_RATES': {
        'anon': '50/hour',
        'user': '1000/day',
        'burst': '10/minute',
        'sustained': '500/day',
        'light': '5/minute',
        'medium': '20/minute',
        'heavy': '100/minute',
    },
}

SPECTACULAR_SETTINGS = {
    'TITLE': 'Invite Ellie API',
    'DESCRIPTION': "Invite Ellie is an AI-powered meeting assistant that transcribes, summarizes, and organizes meeting content in real time.",
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
    'SCHEMA_PATH_PREFIX': r'\/(\w+(?:-\w+)+)*\w+\/api\/',
    # 'SCHEMA_PATH_PREFIX': r'',
    'COMPONENT_SPLIT_REQUEST': True,
    'SECURITY': [
        {
            'Bearer': [],
        },
    ],
    "APPEND_COMPONENTS": {
        "securitySchemes": {
            'Bearer': {
                'type': 'http',
                'scheme': 'bearer',
                'bearerFormat': 'JWT',
            }
        },
    },
    'USE_SESSION_AUTH': False,
    'SWAGGER_UI_SETTINGS': {
        'persistAuthorization': True,
        'filter': True,
        'deepLinking': True,
    },
}

DJANGO_GUID = {
    'GUID_HEADER_NAME': 'X-Correlation-ID',
    'VALIDATE_GUID': True,
    'RETURN_HEADER': True,
    'EXPOSE_HEADER': True,
    'INTEGRATIONS': [],
    'IGNORE_URLS': [],
    'UUID_LENGTH': 32,
}

ADMINS = [
    ('Dev', 'dev@ellie.com'),
    ('Ops', 'ops@ellie.com'),
]

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'json': {
            '()': 'pythonjsonlogger.jsonlogger.JsonFormatter',
            'format': '%(asctime)s %(levelname)s %(name)s %(lineno)s %(correlation_id)s %(user_id)s %(message)s %(exc_info)s %(stack_info)s',
            'datefmt': '%Y-%m-%d %H:%M:%S',
        },
        'verbose': {
            'format': '[%(asctime)s] %(levelname)s [%(name)s:%(lineno)s] '
                      'correlation_id=%(correlation_id)s user_id=%(user_id)s %(message)s',
            'datefmt': '%Y-%m-%d %H:%M:%S'
        },
    },
    'filters': {
        'add_correlation_id': {
            '()': 'django_guid.log_filters.CorrelationId'
        },
        'add_user_id': {
            '()': 'core.logging.UserIDFilter',
        },
    },
    'handlers': {
        'json_file': {
            'level': 'INFO',
            'class': 'logging.handlers.TimedRotatingFileHandler',
            'filename': os.path.join(BASE_DIR, 'logs', 'app.json.log'),
            'when': 'midnight',
            'delay': True,
            'interval': 1,
            'backupCount': 30,
            'formatter': 'json',
            'filters': ['add_correlation_id', 'add_user_id'],
        },
        'file': {
            'level': 'INFO',
            'class': 'logging.handlers.TimedRotatingFileHandler',
            'filename': os.path.join(BASE_DIR, 'logs', 'app.log'),
            'when': 'midnight',
            'delay': True,
            'interval': 30,
            'backupCount': 24,
            'formatter': 'verbose',
            'filters': ['add_correlation_id', 'add_user_id'],
        },
        'throttle_file': {
            'class': 'logging.handlers.TimedRotatingFileHandler',
            'filename': os.path.join(BASE_DIR, 'logs', 'throttle_events.log'),
            'when': 'midnight',
            'delay': True,
            'interval': 30,
            'backupCount': 24,
            'formatter': 'verbose',
        },
        'critical_email': {
            'level': 'CRITICAL',
            'class': 'django.utils.log.AdminEmailHandler',
            'include_html': True,
            'formatter': 'verbose',
            'filters': ['add_correlation_id', 'add_user_id'],
        },
        'console': {
            'level': 'DEBUG',
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
            'filters': ['add_correlation_id', 'add_user_id'],
        },
    },
    'root': {
        'level': 'INFO',
        'handlers': ['json_file', 'file', 'console', 'critical_email'],
    },
    'loggers': {
        # ←←← ADD THIS BLOCK ←←←
        'django.request': {
            'handlers': ['file', 'json_file', 'console'],
            'level': 'WARNING',
            'propagate': False,
        },
        'django.server': {
            'handlers': ['file', 'json_file', 'console'],
            'level': 'ERROR',
            'propagate': False,
        },
        'django.security': {
            'level': 'WARNING',
            'handlers': ['json_file', 'critical_email'],
            'propagate': False,
        },
        # Your app logs
        'accounts': {'level': 'INFO', 'propagate': True},
        'workspaces': {'level': 'INFO', 'propagate': True},
        'core': {'level': 'INFO', 'propagate': True},
        'core.middleware.ThrottleMonitorMiddleware': {  # Logger for the middleware
            'handlers': ['console', 'throttle_file'],
            'level': 'WARNING',
            'propagate': False,
        },
    },
}

CACHE_BACKEND = config("CACHE_BACKEND", default=None)

if CACHE_BACKEND and 'redis' in CACHE_BACKEND.lower():
    CACHES = {
        "default": {
            "BACKEND": CACHE_BACKEND,
            "LOCATION": REDIS_URL,
            "OPTIONS": {
                "CLIENT_CLASS": "django_redis.client.DefaultClient",
            }
        }
    }
else:
    CACHES = {
        "default": {
            "BACKEND": "django.core.cache.backends.filebased.FileBasedCache",
            "LOCATION": os.path.join(BASE_DIR, "django_cache"),
        }
    }

DJANGO_CACHE_BACKEND = config("DJANGO_CACHE_BACKEND", default=None)

if DJANGO_CACHE_BACKEND != None:
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.memcached.PyMemcacheCache',
            'LOCATION': DJANGO_CACHE_BACKEND,
        }
    }


SESSION_COOKIE_AGE = 1800
SESSION_EXPIRE_AT_BROWSER_CLOSE = True
SESSION_COOKIE_SECURE = True
SESSION_COOKIE_HTTPONLY = True
CSRF_COOKIE_SECURE = True

SESSION_COOKIE_SAMESITE = 'None'
CSRF_COOKIE_SAMESITE = 'None'
CSRF_COOKIE_HTTPONLY = False

ANONYMIZATION_SALT = config("ANONYMIZATION_SALT", default="2o234opi5n43i2n5")

STRIPE_SECRET_KEY = config('STRIPE_SECRET_KEY')
STRIPE_PUBLISHABLE_KEY = config('STRIPE_PUBLISHABLE_KEY')
STRIPE_WEBHOOK_SECRET = config('STRIPE_WEBHOOK_SECRET')
STRIPE_PRICE_CLARITY = config('STRIPE_PRICE_CLARITY')
STRIPE_PRICE_INSIGHT = config('STRIPE_PRICE_INSIGHT')
STRIPE_PRICE_ALIGNMENT = config('STRIPE_PRICE_ALIGNMENT')

STRIPE_SUCCESS_URL = config('STRIPE_SUCCESS_URL', default='http://localhost:3000/billing/success')
STRIPE_CANCEL_URL = config('STRIPE_CANCEL_URL', default='http://localhost:3000/billing/cancel')


PERSONAL_EMAIL_DOMAINS = config('PERSONAL_EMAIL_DOMAINS', default='gmail.com,yahoo.com,outlook.com,hotmail.com,aol.com,icloud.com,protonmail.com,live.com,msn.com,gmx.com,me.com,mac.com,ymail.com,rocketmail.com,hushmail.com,tutanota.com', cast=Csv())


JAZZMIN_SETTINGS = {
    # General look & feel
    "site_title": "Invite Ellie Admin",
    "site_header": "Invite Ellie",
    "site_brand": "Invite Ellie",
    "site_logo": None,  # or "/static/images/logo.png" if you have one
    "welcome_sign": "Welcome to Invite Ellie Admin Panel",
    "copyright": "Invite Ellie © 2025",

    # Search
    "search_model": [
        "accounts.Profile",
        "workspaces.Meeting",
        "accounts.DeletionAuditLog",
    ],

    # Top menu links
    "topmenu_links": [
        {"name": "Live Site", "url": "https://inviteellie.ai", "new_window": True},
        {"name": "Staging Site", "url": "https://stage.inviteellie.ai", "new_window": True},
        {"model": "accounts.Profile", "label": "Profiles"},
    ],

    # Sidebar
    "show_sidebar": True,
    "navigation_expanded": True,
    "hide_apps": ["auth"],  # hide default auth if you don't need it

    # Icons for models (Font Awesome)
    "icons": {
        "auth": "fas fa-users-cog",
        "auth.User": "fas fa-user",
        "accounts.Profile": "fas fa-user-circle",
        "accounts.DeletionAuditLog": "fas fa-shield-alt",
        "workspaces.Meeting": "fas fa-video",
        "workspaces.Workspace": "fas fa-briefcase",
        "workspaces.Folder": "fas fa-folder",
    },

    # UI features
    "default_ui_toggler": True,          # show dark/light toggle
    "show_ui_toggler": True,
    "changeform_format": "vertical_tabs", # or "horizontal_tabs", "single"
    "show_theme_switch": True,

    # Custom colors / branding
    "theme": "default",  # or "darkly", "flatly", "cosmo", "cerulean", etc.
    "custom_css": None,
    "custom_js": None,

    # Dashboard widgets (optional but very useful)
    "dashboard": {
        "welcome": True,
        "recent_actions": True,
        "quick_links": [
            {"name": "Pending Deletions", "url": "/admin/accounts/profile/?deletion_requested_at__isnull=False&deletion_completed_at__isnull=True"},
            {"name": "Active Legal Holds", "url": "/admin/accounts/profile/?legal_hold=True"},
        ],
    },
}