"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
from datetime import timedelta
from decouple import config, Csv
from django.core.files.storage import FileSystemStorage
import dj_database_url

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

LOG_DIR = BASE_DIR / 'logs'
LOG_DIR.mkdir(exist_ok=True)  # This fixes the error

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config(
    "DJANGO_SECRET_KEY",
    default="19WjHUSl2rb8h29fSRRQ62uJiJAfT8m1emybJYuNw5uHROfRPcqFXWZQFO90bDyxM2",
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config("DJANGO_DEBUG", default=False)

ALLOWED_HOSTS = ["*"]
CORS_ALLOW_METHODS = [
    "DELETE",
    "GET",
    "OPTIONS",
    "PATCH",
    "POST",
    "PUT",
]
CORS_ALLOW_ALL_ORIGINS = config("CORS_ALLOW_ALL_ORIGINS", default=True)


INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'django_filters',
    'django_extensions',
    'django_guid',
    'drf_spectacular',
    'rest_framework',
    'corsheaders',
    'storages',

    'accounts',

]

MIDDLEWARE = [
    'django_guid.middleware.guid_middleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'accounts.middleware.SupabaseJWTAuthentication',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'

# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases
DATABASES = {
    'default': dj_database_url.parse(config('DATABASE_URL'))
}
# REQUIRED for Supabase Pooler (Supavisor)
DATABASES['default']['OPTIONS'] = {
    'sslmode': 'require',           # SSL is mandatory
    'server_side_binding': True,    # Required in transaction mode
}
# Reuse connections (optional but recommended)
DATABASES['default']['CONN_MAX_AGE'] = 60


SUPABASE_URL=config("SUPABASE_URL")
SUPABASE_ANON_KEY=config("SUPABASE_ANON_KEY")
SUPABASE_SERVICE_ROLE_KEY=config("SUPABASE_SERVICE_ROLE_KEY")
OPENAI_API_KEY=config("OPENAI_API_KEY")
REDIS_URL=config("REDIS_URL")
SUPABASE_JWT_SECRET=config("SUPABASE_JWT_SECRET")

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

MEDIA_ROOT = str(BASE_DIR / "media")
MEDIA_URL = "/media/"

FRONTEND_CONFIG = {
    "FRONTEND_URL": config("FRONTEND_URL", default="http://localhost:3000/"),
    "PASSWORD_RESET_URL": "password/reset/confirm/",
    "EMAIL_CONFIRM_URL": "verify_email/",
}

EMAIL_BACKEND = config(
    "DJANGO_EMAIL_BACKEND", default="django.core.mail.backends.console.EmailBackend",
)

CELERY_TASK_ALWAYS_EAGER = config("CELERY_TASK_ALWAYS_EAGER", default=True, cast=bool)         # SKIP THE QUEUE
CELERY_TASK_EAGER_PROPAGATES = config("CELERY_TASK_EAGER_PROPAGATES", default=True, cast=bool)     # SKIP THE QUEUE

REST_FRAMEWORK = {
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 10,
    'PAGE_SIZE_QUERY_PARAM': 'page_size',
    'DEFAULT_AUTHENTICATION_CLASSES': [],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
}

SPECTACULAR_SETTINGS = {
    'TITLE': 'Invite Ellie MVP API',
    'DESCRIPTION': "MVP",
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
    # 'SCHEMA_PATH_PREFIX': r'\/(\w+(?:-\w+)+)*\w+\/api\/',
    # 'SCHEMA_PATH_PREFIX': r'',
    'COMPONENT_SPLIT_REQUEST': True,
    'SECURITY': [
        {
            'Bearer': [],
        },
    ],
    "APPEND_COMPONENTS": {
        "securitySchemes": {
            'Bearer': {
                'type': 'http',
                'scheme': 'bearer',
                'bearerFormat': 'JWT',
            }
        },
    },
    'USE_SESSION_AUTH': False,
    'SWAGGER_UI_SETTINGS': {
        'persistAuthorization': True,
        'filter': True,
        'deepLinking': True,
    },
}

DJANGO_GUID = {
    'GUID_HEADER_NAME': 'X-Correlation-ID',
    'VALIDATE_GUID': True,
    'RETURN_HEADER': True,
    'EXPOSE_HEADER': True,
    'INTEGRATIONS': [],
    'IGNORE_URLS': [],
    'UUID_LENGTH': 32,
}

ADMINS = [
    ('Dev', 'dev@ellie.com'),
    ('Ops', 'ops@ellie.com'),
]

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '[%(asctime)s] %(levelname)s [%(name)s:%(lineno)s] '
                      'correlation_id=%(correlation_id)s user_id=%(user_id)s %(message)s',
            'datefmt': '%Y-%m-%d %H:%M:%S'
        },
    },
    'filters': {
        'add_correlation_id': {
            '()': 'django_guid.log_filters.CorrelationId'
        },
        'add_user_id': {
            '()': 'core.logging.UserIDFilter',
        },
    },
    'handlers': {
        'file': {
            'level': 'INFO',
            'class': 'logging.handlers.TimedRotatingFileHandler',
            'filename': os.path.join(BASE_DIR, 'logs', 'app.log'),
            'when': 'midnight',
            'backupCount': 10,
            'formatter': 'verbose',
            'filters': ['add_correlation_id', 'add_user_id'],
        },
        'critical_email': {
            'level': 'CRITICAL',
            'class': 'django.utils.log.AdminEmailHandler',
            'include_html': True,
            'formatter': 'verbose',
            'filters': ['add_correlation_id', 'add_user_id'],
        },
        'console': {
            'level': 'DEBUG',
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
            'filters': ['add_correlation_id', 'add_user_id'],
        },
    },
    'loggers': {
        '': {
            'handlers': ['file', 'console', 'critical_email'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}

CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.filebased.FileBasedCache",
        "LOCATION": os.path.join(BASE_DIR, "django_cache"),
    }
}

DJANGO_CACHE_BACKEND = config("DJANGO_CACHE_BACKEND", default=None)

if DJANGO_CACHE_BACKEND != None:
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.memcached.PyMemcacheCache',
            'LOCATION': DJANGO_CACHE_BACKEND,
        }
    }
